# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

project 'augmented-identity.xcodeproj'
target 'augmented-identity' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TextTest
  pod 'TextFieldEffects'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
end
